config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
  end

  root to: "homes#index"
  resources :videos do
    collection do
      get 'search'
    end
    resources :orders, only: [:new, :create]
    resources :comments, only: [:create]
  end
  resources :profiles, only: [:show, :edit, :update]
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, optional: true
  has_one_attached :image
  has_many :videos
  has_many :orders
  has_many :comments, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :sex
  belongs_to :genre
  belongs_to :prefecture

  with_options presence: true do
    validates :image, :nickname
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:nickname, :sex_id, :genre_id, :prefecture_id, :birthday, :biography,
                                    :image).merge(user_id: current_user.id)
  end
end

app/views/profiles/edit.html.erb
<%= render "shared/second-header"%>

<%= form_with model: @profile, class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      日本中のかっこいいダンサーを発掘しよう！
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">プロフィール画像</label>
      <span class="indispensable">必須</span>
    </div>
    <div class="click-upload">
      <p>
        クリックしてファイルをアップロード
      </p>
      <%= f.file_field :image, id:"item-image" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"ニックネーム", maxlength:"40" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">性別</label>
      <span class="form-any">任意</span>
    </div>
    <%= f.collection_select(:sex_id, Sex.all, :id, :name, {}, {class:"select-box", id:"sex"}) %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ジャンル</label>
      <span class="form-any">任意</span>
    </div>
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"genre"}) %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">レペゼン</label>
      <span class="form-any">任意</span>
    </div>
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="form-any">任意</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>

  <div class="new-bio">
    <div class='form-text-wrap'>
      <label class="form-text">背景</label>
      <span class="form-any">任意</span>
    </div>
    <%= f.text_area :biography, class:"bio-text", id:"biography", placeholder:"bio", rows:"5", maxlength:"1000" %>
  </div>

  <%# 下部ボタン %>
  <div class="sell-btn-contents">
    <%= f.submit "変更する" ,class:"sell-btn" %>
    <%=link_to 'もどる', edit_profile_path(@profile.id), class:"back-btn" %>
  </div>
  <%# /下部ボタン %>
</div>
<% end %>

app/views/profiles/show.html.erb
<%= render "shared/header" %>

<%# プロフィールの概要 %>
<div class="profile-show">
  <div class="profile-box">
    <div class="right-contents">
      <%= image_tag(@profile.image, class: "profile-img") %>
    </div>
    <div class="left-contents">
      <ul class="profile-main">
        <li class="profile-name">
          <div class="nickname"><%= @profile.nickname%></div>
          <div class="sex"><%= @profile.sex.name %></div>
        </li>
        <li class="profile-introduction">
          <div class="profile-detail"><%= @profile.birthday %></div>
          <div class="profile-detail"><%= @profile.prefecture.name %></div>
          <div class="profile-detail"><%= @profile.genre.name %></div>
        </li>
        <li class="profile-bio">
          <%= @profile.biography%>
        </li>
      </ul>
    </div>
  </div>
  <%#/ プロフィールの概要 %>

  <%# 下部ボタン %>
  <% if current_user.id == @profile.id %>
    <div class="profile-btn-contents">
      <%= link_to '編集する', edit_profile_path(current_user.profile.id), class:"edit-btn" %>
      <%= link_to "もどる" , "/",class:"back-btn" %>
    </div>
  <% else %>
  <% end %>
  <%# /下部ボタン %>
</div>