config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
  end

  root to: "homes#index"
  resources :videos do
    collection do
      get 'search'
    end
    resources :orders, only: [:new, :create]
    resources :comments, only: [:create]
  end
  resources :profiles, only: [:show, :edit, :update]
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  has_one_attached :video
  belongs_to :profile
  has_many :orders
  has_many :comments, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :prefecture

  with_options presence: true do
    validates :video, :title, :introduction
    validates :price,
              numericality: { only_integer: true, greater_than_or_equal_to: 100, less_than_or_equal_to: 9_999_999,
                              message: 'is invalid. Price is out of setting range' }
  end

  validates :genre_id, :prefecture_id,
            numericality: { other_than: 1, message: "can't be blank" }
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_video, except: [:index, :new, :create, :search]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    @videos = Video.where(prefecture_id: params[:prefecture_id])
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @order = Order.find(params[:id]) unless @video.orders.blank?
    @comment = Comment.new
    @comments = @video.comments.includes(:user).order('created_at DESC')
  end

  def edit
  end

  def update
    if @video.update(video_params)
      redirect_to video_path(@video.id)
    else
      render :edit
    end
  end

  def destroy
    @video.destroy
    redirect_to root_path
  end

  private

  def video_params
    params.require(:video).permit(:title, :introduction, :genre_id, :prefecture_id, :price,
                                  :video).merge(user_id: current_user.id, profile_id: current_user.profile.id)
  end

  def set_video
    @video = Video.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @video.user
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_video.html.erb
<% @videos.each do |video| %>
  <li class='list'>
    <%= link_to video_path(video.id), method: :get do %>
      <%# 動画の表示 %>
      <% if user_signed_in? %>
        <% if current_user.id == video.user_id or Order.find_by(user_id: current_user.id, video_id: video.id).present?%>
          <div class="video-img-content">
            <video src="<%= rails_blob_path(video.video) %>" class="video-img" type="video/mp4" controls></video>
        <% else %>
          <div class="video-img-content">
            <%= video_tag rails_blob_path(video.video), class: "video-img" %>
        <% end %>
      <% else %>
        <div class="video-img-content">
          <%= video_tag rails_blob_path(video.video), class: "video-img" %>
      <% end %>	
      <%#/ 動画の表示 %>
      <div class='video-info'>
        <h3 class='video-name'>
          <%= video.title %>
        </h3>
        <div class='video-price'>
          <span><%= video.price %>円<br></span>
          <div class='star-btn'>
            <%= image_tag "star.png", class:"star-icon" %>
            <span class='star-count'>0</span>
          </div>
        </div>
      </div>
    <% end %>
  </li>
<% end %>

app/views/videos/edit.html.erb
<div class="videos-post-contents">
  <header class="videos-post-header">
    <%= render "shared/second-header"%>

  </header>
  <div class="videos-post-main">
    <h2 class="videos-post-title">Pick Out</h2>
    <%= form_with model: @video, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 投稿動画 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        Dance Movie
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :video, id:"post-video" %>
      </div>
    </div>
    <%# /投稿動画 %>
    <%# 動画名と動画説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        Title
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"例）Line Dance in OKAYAMA（40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          Description
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :introduction, class:"items-text", id:"item-info", placeholder:"動画の説明（必須 1,000文字まで）(MusicName, DancerName, Place etc.)" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /動画名と動画説明 %>

    <%# 動画の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">Detail</div>
      <div class="form">
        <div class="weight-bold-text">
          Genre
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"video-genre"}) %>
        <div class="weight-bold-text">
          Repezen
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"video-prefecture"}) %>
      </div>
    </div>
    <%# /動画の詳細 %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>Price<br>(¥100〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', video_path(@video.id), class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>

app/views/videos/index.html.erb
<%= render "shared/header" %>

  <%# 動画一覧 %>
  <div class='video-contents'>
    <h2 class='title'>ピックアップ</h2>
    <ul class='video-lists'>
      <% @videos.each do |video| %>
        <li class='list'>
          <%= link_to video_path(video.id), method: :get do %>
            <%# 動画の表示 %>
            <% if user_signed_in? %>
              <% if current_user.id == video.user_id or Order.find_by(user_id: current_user.id, video_id: video.id).present?%>
                <div class="video-img-content">
                  <video src="<%= rails_blob_path(video.video) %>" class="video-img" type="video/mp4" controls></video>
              <% else %>
                <div class="video-img-content">
                  <%= video_tag rails_blob_path(video.video), class: "video-img" %>
              <% end %>
            <% else %>
              <div class="video-img-content">
                <%= video_tag rails_blob_path(video.video), class: "video-img" %>
            <% end %>	
            <%#/ 動画の表示 %>
            <div class='video-info'>
              <h3 class='video-name'>
                <%= video.title %>
              </h3>
              <div class='video-price'>
                <span><%= video.price %>円<br></span>
                <div class='star-btn'>
                  <%= image_tag "star.png", class:"star-icon" %>
                  <span class='star-count'>0</span>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <%# /動画一覧 %>
</div>

app/views/videos/new.html.erb
<div class="videos-post-contents">
  <header class="videos-post-header">
    <%= render "shared/second-header"%>

  </header>
  <div class="videos-post-main">
    <h2 class="videos-post-title">Pick Out</h2>
    <%= form_with model: @video, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 投稿動画 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        Dance Movie
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :video, id:"post-video" %>
      </div>
    </div>
    <%# /投稿動画 %>
    <%# 動画名と動画説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        Title
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"例）Line Dance in OKAYAMA（40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          Description
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :introduction, class:"items-text", id:"item-info", placeholder:"動画の説明（必須 1,000文字まで）(MusicName, DancerName, Place etc.)" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /動画名と動画説明 %>

    <%# 動画の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">Detail</div>
      <div class="form">
        <div class="weight-bold-text">
          Genre
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"video-genre"}) %>
        <div class="weight-bold-text">
          Repezen
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"video-prefecture"}) %>
      </div>
    </div>
    <%# /動画の詳細 %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>Price<br>(¥100〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"video-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>

app/views/videos/search.html.erb
<%= render "shared/header" %>
<div class='main'>
  <%# 商品一覧 %>
  <div class='video-contents'>
    <div class="video-container">
      <ul class='video-lists'>
          <%= render partial:"video", collection: @videos, locals: {video: @videos} %>
      </ul>
    </div>
  </div>
  <%# /商品一覧 %>
</div>

app/views/videos/show.html.erb
<%= render "shared/header" %>

<%# 動画の概要 %>
<div class="video-show">
  <div class="video-box">
    <h2 class="name">
      <%= @video.title %>
    </h2>
  <%# 動画の表示 %>
  <%# 動画が再生できるのは投稿者か購入者%>
  <% if user_signed_in? %>
    <% if current_user.id == @video.user_id or current_user.id == @order&.user_id %>
      <div class="video-img-content">
        <video src="<%= rails_blob_path(@video.video) %>" class="video-img" type="video/mp4" controls></video>
      </div>
    <% else %>
      <div class="video-img-content">
        <%= video_tag rails_blob_path(@video.video), class: "video-img" %>
      </div>
    <% end %>
  <% else %>
    <div class="video-img-content">
      <%= video_tag rails_blob_path(@video.video), class: "video-img" %>
    </div>
  <% end %>
  <%#/ 動画の表示 %>

    <div class="video-price-box">
      <span class="video-price">
        <%= "¥ #{@video.price}" %> 
      </span>
    </div>
  <%# 動画のボタンの表示 %>
    <% if user_signed_in? %>
      <% if current_user.id == @video.user_id %>
        <%= link_to "編集", edit_video_path(@video.id), method: :get, class: "video-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", video_path(@video.id), method: :delete, class:"video-destroy" %>
      <% elsif current_user.id != @order&.user_id%>
        <%= link_to "購入画面に進む", new_video_order_path(@video.id),class:"video-red-btn"%>
      <% else %>
      <% end %>
    <% end %>
  <%#/ 動画のボタンの表示 %>

    <div class="video-introduction-box">
      <span><%= @video.introduction %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-video">出品者</th>
          <td class="detail-value"><%=link_to @video.profile.nickname, profile_path(@video.profile.id) %></td>
        </tr>
        <tr>
          <th class="detail-video">ジャンル</th>
          <td class="detail-value"><%= @video.genre.name %></td>
        </tr>
        <tr>
          <th class="detail-video">レペゼン</th>
          <td class="detail-value"><%= @video.prefecture.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>
  <%# /動画の概要 %>
  <div class="container">
    <% if user_signed_in? && current_user.id == @video.user_id or Order.find_by(user_id: current_user.id, video_id: @video.id).present? %>
      <%= form_with(model: [@video, @comment], local: true) do |f| %>
        <div class="comment-field">
          <h4>＜コメント投稿＞</h4>
          <div class="field" id="star">
            <%= f.label :value, "星評価：" %>
            <%= f.hidden_field :value, id: :review_star %>
            <script>
              $('#star').raty({
                size     : 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                scoreName: 'comment[value]',
                half: true,
              });
            </script>
          </div>
          <div class="comment-box">
            <%= f.text_field :text,class:"comment-text", placeholder: "Evaluate the video", rows: "1" %>
            <div class='comment-btn'>
              <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
              <%= f.submit "送信", class: "comment-lb-btn" %>             
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <div class="relative-comment-evaluation">
          <span>評価：</span>
          <span id="star-rate-<%= comment.id %>"></span>
          <script>
            $('#star-rate-<%= comment.id %>').raty({
              size: 36,
              starOff: "<%= asset_path('star-off.png') %>",
              starOn: "<%= asset_path('star-on.png') %>",
              starHalf: "<%= asset_path('star-half.png') %>",
              half: true,
              readOnly: true,
              score: "<%= comment.value %>",
            });
          </script>
          <%= comment.value %>
          <p>
            <strong><%= link_to comment.profile.nickname, profile_path(comment.profile.id) %>：</strong>
            <%= comment.text %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class="another-item"><%= @video.genre.name %>をもっと見る</a>
</div>