config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
  end

  root to: "homes#index"
  resources :videos do
    collection do
      get 'search'
    end
    resources :orders, only: [:new, :create]
    resources :comments, only: [:create]
  end
  resources :profiles, only: [:show, :edit, :update]
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>

</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to 'FURIMAガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("furima-logo-white.png", class:"logo-white"), "#" %>
  <p>© FURIMA</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("Digger-logo.png", class:"digger-icon"), "/" %>
    <%= search_form_for @q, url: search_videos_path, class:"search-form" do |f| %>
      <%= f.search_field :title_cont, placeholder: '検索', class:'input-box' %>
      <%= f.button type: "submit", class:"search-button" do%>
        <%= image_tag "search.png", class:"search-icon" %>
      <% end %>
    <% end %>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
      <li><%= link_to image_tag('post_icon.png', class: "video-post"), new_video_path %></li>
    </ul>
    <ul class='lists-right'>
    <% if user_signed_in? %>
      <li><%= image_tag(current_user.profile.image, class: "profile-image", id: "lists") %></li>
      <ul class="show-lists hidden" id="pull-down">
        <li class="pull-down-list"><%= link_to current_user.profile.nickname, profile_path(current_user.profile.id) %></li>
        <li class="pull-down-list"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <li class="pull-down-list">リスト3</li>
        <li class="pull-down-list">リスト4</li>
      </ul>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("Digger-logo2.png", class:"second-logo"), "/" %>
</header>